# docker-compose for BazaarBrain-Pro (backend only)
# Usage:
#   docker compose -f deploy/docker-compose.yml up --build

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: bazaarbrain-backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env.production
    restart: unless-stopped
